### ISSUE TITLE
Cache is hardcoded to ~/.cache/, leads to windows usability problems.

### ISSUE THREAD

**Issue by tazlin** [Sygil-Dev/nataili#102]
nataili.cache being tied to the user's home directory means that, in practice, users on Windows will be forced to use their Windows install drive, which may be an annoyance or highly undesirable. In the case of having limited or no disk space left, users will be unable to use the project as intended. Additionally, some *NIX users may find this behavior undesirable.

I am recommending the call to ` self.path = f"{Path.home()}/.cache/nataili/"` in `cache.py` be replaced with a suitable lookup to either a well established environment variable, such as XDG_CACHE_HOME or, must less preferably, a custom environment variable. 

Additionally, I recommend that you do not use the common name of `.cache`, and prefer `nataili/.cache` as just `.cache` in a common place introduces the possibility it may be confused for another folder of the same name, by a user or a program alike.

**Comment by db0** [comment]
Yep, this will be needed for the worker as we need a way to keep everything compartmentalized in the install location

**Comment by db0** [comment]
I'll see if I can push the fix myself

**Comment by tazlin** [comment]
Having looked into this further, it was a systematic problem throughout the code with calls to `Path.home()` throughout the code base, and not just this `Cache` object as I originally suspected. #103 makes an attempt at addressing this.

**Comment by hlky** [comment]
I had considered using `~/.nataili` but using `~/.cache` is common
![image](https://user-images.githubusercontent.com/106811348/217029283-977950e5-9e03-404c-886e-c8ef2b9a17a4.png)

**Comment by tazlin** [comment]
I have no dog in the fight if the behavior for `~/.cache` is overridable via environment variable. If the primary use case is horde workers, its going to be overridden in that case, and I'll trust that any other protentional consumers of this library will make their own decision.

**Comment by hlky** [comment]
#103
