### ISSUE TITLE
voodoo.py: "UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors"

### ISSUE THREAD

**Issue by tazlin** [Sygil-Dev/nataili#126]
>`...\hlky\AI-Horde-Worker\conda\envs\windows\lib\site-packages\nataili\util\voodoo.py:74: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at c:\cb\pytorch_1000000000000\work\torch\csrc\utils\tensor_numpy.cpp:205.)`
voodoo.py line 74:
>`module.register_buffer(name, torch.as_tensor(array, device=device))`

I am unsure of the specific ramifications of this. Is this benign? Can the warning be safely suppressed?

**Comment by hlky** [comment]
Safe to ignore, [8b97bf0](https://github.com/Sygil-Dev/nataili/commit/8b97bf0321cca1b23f8cc1047d52111cd0eb20c5) should suppress the warnings.

Note: AI-Horde-Worker is using v0.0.1, so this fix won't apply there until [AI-Horde-Worker updates](https://github.com/db0/AI-Horde-Worker/pull/36). This should be soon:tm:
