### ISSUE TITLE
Add support for optional progress bars

### ISSUE THREAD

**Issue by jug-dev** [Sygil-Dev/nataili#127]
Currently progress bars are hardcoded enabled. As a library that may be used server-side (or unit tested), it would be nice if these animated progress bars were optional.

As requested here https://github.com/db0/AI-Horde-Worker/pull/31

**Comment by jug-dev** [comment]
The Nataili library hardcodes terminal progress bars in 30 places. Most of that is within `ldm` and `ldm2`. Are `ldm` and `ldm2` considered upstream to nataili or are they part of the nataili codebase to be modified?

A feature to disable progress bars via environmental variables in tqdm has been requested [many times](https://github.com/tqdm/tqdm/issues/612) for many years. It's never been added that I can see.

Nataili's bespoke Switch() construct doesn't seem much use as it isn't applicable to `ldm` or `ldm2` A simple solution here would be to add `disable=os.getenv("DISABLE_TQDM", False)` to each tqdm call across `nataili`, `ldm` and `ldm2`. Is that acceptable? 

This would allow unit tests or server side users of nataili to disable the animated progress bar with a simple environmental variable.

**Comment by hlky** [comment]
`ldm` and `ldm2` can be modifed (and will be combined at some point)

`disable=os.getenv("DISABLE_TQDM", False)` seems like an acceptable solution to me

@db0 do we want progress bars disabled by default?

**Comment by db0** [comment]
For the horde worker yes, but I others using nataili might wish them do a way to turn them back on globally (say with an env variable or a Switch class) might be useful

**Comment by db0** [comment]
The Switch class can also easily be used as I do with Ray and xformers, but I'll be leave it up to you you which you prefer

**Comment by jug-dev** [comment]
I'm not sure I like it. Lemme try Switch

**Comment by jug-dev** [comment]
Personally I think I prefer the Switch() in #129
