### ISSUE TITLE
3 pixel wide results

### ISSUE THREAD

**Issue by ChucklesTheBeard** [Sygil-Dev/nataili#58]
If the job sets `use_nsfw_censor = True`, the bridgeData.py `censorlist` ~~is empty~~ is NOT empty, and bridgeData.py `censor_nsfw = False`, 3 pixel wide results are always returned.

example: https://cdn.discordapp.com/attachments/1020695869927981086/1041557681833508914/unknown.png

Workaround: use the blacklist instead of censorlist.

Fix, part 1: 
* figure out what the censor_nsfw flag in bridgeData is specifically meant to achieve
* figure out what the use_nsfw_censor flag in jobs is specifically meant to achieve, in relation to the above.

(edit: happens when censorlist is NOT empty, my bad)

**Comment by db0** [comment]
censor_nsfw flag in bridgeData is used in SFW workers to ensure they don't generate NSFW

use_nsfw_censor from clients is used for SFW requests to ensure they don't generate NSFW

The problem is the safety filter generating this 3px image instead of censoring properly with a black image

**Comment by ChucklesTheBeard** [comment]
Is the intent to not generate nsfw images adequately expressed with the
other nsfw flag?

With the settings mentioned the safety_filter doesn't seem to trigger on an
nsfw detection, it just corrupts all images passing through it.

If the worker has censoring turned off, presently it doesn't matter if the
job requests it, because a worker with the safety checker unloaded will be
sent the job, and will return a nsfw image anyway.

**Comment by AlRlC** [comment]
When I tested earlier, the worker in question had blacklist empty, censorlist with words. I sent requests to the horde
with nsfw = enabled
```
prompt: Beach, mountains, water (Returned with a valid generation)
prompt: 1girl, adult (returned 3px image)
```

currently I think the concern is that if a user requests a prompt with nsfw generation being allowed, they will sometimes get good generations or randomly bad generation (either 3px or a regular black image)
