### ISSUE TITLE
ModuleNotFoundError: No module named 'bridgeData'

### ISSUE THREAD

**Issue by clankill3r** [Sygil-Dev/nataili#73]
When I run `horde-bridge.cmd` I get the following:

> C:\Users\HSLab\Desktop\nataili>.\horde-bridge.cmd
> The operation completed successfully.
> 2022-12-08 10:06:12,546 INFO worker.py:1528 -- Started a local Ray instance.
> INIT       | Prepared    | Ray temp dir 'C:\Users\HSLab\Desktop\nataili\ray'
> Traceback (most recent call last):
>   File "bridge.py", line 10, in <module>
>     from worker.bridge_data import BridgeData
>   File "C:\Users\HSLab\Desktop\nataili\worker\bridge_data.py", line 9, in <module>
>     import bridgeData as bd
> ModuleNotFoundError: No module named 'bridgeData'
> The operation completed successfully.

**Comment by db0** [comment]
copy bridgeData_template.py to bridgeData.py and edit it
