### ISSUE TITLE
Windows QuickEdit Mode Freeze Scripts

### ISSUE THREAD

**Issue by freeload101** [Sygil-Dev/nataili#91]
I had this issue for about 1000 years but just now fixed it.. I thought it was broken for hours when I had just clicked the window and activated QuickEdit mode stopping the output.

If you click a command prompt window it will stop the output and possibly break the script

maybe add this to the horde-bridge.cmd

`reg add HKCU\Console /v QuickEdit /t REG_DWORD /d 0 /f`

Reference:
https://stackoverflow.com/questions/30418886/how-and-why-does-quickedit-mode-in-command-prompt-freeze-applications

Or only at runtime:

Disable in python: ?
https://stackoverflow.com/questions/41409727/turn-off-windows-10-console-mark-mode-from-my-application

Powershell:
https://gist.github.com/daviwil/edd9a55cf64c9d4f19d1c9c94ff4c3e3 

csc.exe
https://github.com/npocmaka/batch.scripts/blob/master/hybrids/.net/c/quickEdit.bat

**Comment by db0** [comment]
Oh I didn't know one could stop this. Cool

**Comment by hlky** [comment]
#120 Will add this to Documentation, thanks
