### ISSUE TITLE
Download models manually

### ISSUE THREAD

**Issue by DumoeDss** [Sygil-Dev/nataili#95]
The program always fails to download the model, and the speed is very slow. Can you provide the download address of the model and copy it to the folder after downloading it manually?

**Comment by DumoeDss** [comment]
And the model in aitemplate.json always fails to download

**Comment by db0** [comment]
Something is wrong with your setup if it's always failing to download. Can you increase your `max_models_to_download` value and check if it helps?

**Comment by DumoeDss** [comment]
No, the model download failure is caused by network instability, usually the speed drops to 0 after a partial download, then I have to force close and reopen the program.
And the file in aitemplate.json I tried to access directly using a browser or downloading software is not accessible.

**Comment by db0** [comment]
You can find all the files it's downloading here as well as the location it's storing them https://github.com/Sygil-Dev/nataili-model-reference/blob/main/db.json

**Comment by DumoeDss** [comment]
Get it, Thank you~
